FROM node:16-alpine as build

WORKDIR /usr/token-manager/app

COPY package*.json .

RUN npm install

COPY . .

RUN npm run build

COPY ./src/tokens/contracts ./dist/tokens/contracts

FROM node:16-alpine as production

ARG ENV_ARG=production
ENV NODE_ENV=${ENV_ARG}

WORKDIR /usr/token-manager/app

COPY package*.json .

RUN npm install --production

COPY --from=build /usr/token-manager/app/dist ./dist

COPY --from=build /usr/token-manager/app/dist/tokens/contracts ./dist/tokens/contracts

CMD ["node", "./dist/index.js"]